/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonComponent {
        "classes": string;
        "color": string;
        "component": string;
        "disableElevation": boolean;
        /**
          * @default false
         */
        "disableFocusRipple": boolean;
        /**
          * @default false
         */
        "disableRipple": boolean;
        "disabled": string;
        "endIcon": Node;
        /**
          * @default false
         */
        "fullWidth": boolean;
        "href": string;
        /**
          * @default false
         */
        "loading": boolean;
        "loadingIndicator": Node;
        /**
          * @default 'center'
         */
        "loadingPosition": 'center' | 'end' | 'start';
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        "startIcon": Node;
        "sx": object;
        /**
          * @default 'text'
         */
        "variant": 'contained' | 'outlined' | 'text';
    }
    interface ModalComponent {
    }
}
declare global {
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLModalComponentElement extends Components.ModalComponent, HTMLStencilElement {
    }
    var HTMLModalComponentElement: {
        prototype: HTMLModalComponentElement;
        new (): HTMLModalComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-component": HTMLButtonComponentElement;
        "modal-component": HTMLModalComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonComponent {
        "classes"?: string;
        "color"?: string;
        "component"?: string;
        "disableElevation"?: boolean;
        /**
          * @default false
         */
        "disableFocusRipple"?: boolean;
        /**
          * @default false
         */
        "disableRipple"?: boolean;
        "disabled"?: string;
        "endIcon"?: Node;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        "href"?: string;
        /**
          * @default false
         */
        "loading"?: boolean;
        "loadingIndicator"?: Node;
        /**
          * @default 'center'
         */
        "loadingPosition"?: 'center' | 'end' | 'start';
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        "startIcon"?: Node;
        "sx"?: object;
        /**
          * @default 'text'
         */
        "variant"?: 'contained' | 'outlined' | 'text';
    }
    interface ModalComponent {
    }
    interface IntrinsicElements {
        "button-component": ButtonComponent;
        "modal-component": ModalComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "modal-component": LocalJSX.ModalComponent & JSXBase.HTMLAttributes<HTMLModalComponentElement>;
        }
    }
}
