/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonComponent {
        "classes": string;
        "component": string;
        "disableElevation": boolean;
        /**
          * @default false
         */
        "disableFocusRipple": boolean;
        /**
          * @default false
         */
        "disableRipple": boolean;
        "disabled": boolean;
        "endIcon": Node;
        /**
          * @default false
         */
        "fullWidth": boolean;
        "href": string;
        /**
          * @default false
         */
        "loading": boolean;
        "loadingIndicator": Node;
        /**
          * @default 'center'
         */
        "loadingPosition": 'center' | 'end' | 'start';
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        "startIcon": Node;
        "sx": object;
        /**
          * @default 'text'
         */
        "variant": 'contained' | 'outlined' | 'text';
    }
    interface ModalComponent {
        "open": boolean;
    }
}
export interface ModalComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModalComponentElement;
}
declare global {
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLModalComponentElementEventMap {
        "handleClose": void;
    }
    interface HTMLModalComponentElement extends Components.ModalComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModalComponentElementEventMap>(type: K, listener: (this: HTMLModalComponentElement, ev: ModalComponentCustomEvent<HTMLModalComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModalComponentElementEventMap>(type: K, listener: (this: HTMLModalComponentElement, ev: ModalComponentCustomEvent<HTMLModalComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModalComponentElement: {
        prototype: HTMLModalComponentElement;
        new (): HTMLModalComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-component": HTMLButtonComponentElement;
        "modal-component": HTMLModalComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonComponent {
        "classes"?: string;
        "component"?: string;
        "disableElevation"?: boolean;
        /**
          * @default false
         */
        "disableFocusRipple"?: boolean;
        /**
          * @default false
         */
        "disableRipple"?: boolean;
        "disabled"?: boolean;
        "endIcon"?: Node;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        "href"?: string;
        /**
          * @default false
         */
        "loading"?: boolean;
        "loadingIndicator"?: Node;
        /**
          * @default 'center'
         */
        "loadingPosition"?: 'center' | 'end' | 'start';
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        "startIcon"?: Node;
        "sx"?: object;
        /**
          * @default 'text'
         */
        "variant"?: 'contained' | 'outlined' | 'text';
    }
    interface ModalComponent {
        "onHandleClose"?: (event: ModalComponentCustomEvent<void>) => void;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "button-component": ButtonComponent;
        "modal-component": ModalComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "modal-component": LocalJSX.ModalComponent & JSXBase.HTMLAttributes<HTMLModalComponentElement>;
        }
    }
}
